server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory_service
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true